
pub = [dir_path] ../include
include $pub

lib{re2}: $pub/{$($pub/ pub_hdrs)} hxx{**} cxx{**}

# Build options.
#
out_pfx_inc = [dir_path] $out_root/include/
src_pfx_inc = [dir_path] $src_root/include/
cxx.poptions =+ "-I$out_root" "-I$src_root" \
                "-I$src_pfx_inc" "-I$src_base"

# Export options.
#
lib{re2}: cxx.export.poptions = "-I$out_root" "-I$src_root" "-I$src_pfx_inc"

if($cxx.target.class != windows)
  cxx.libs = -lpthread

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{re2}: bin.lib.version = @"-$version.project_id"
else
  lib{re2}: bin.lib.version = @"-$version.major.$version.minor" linux@9


hxx{**}: install = false